# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Trigger AWS CodePipeline
      uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
      #env:
          #AWS_PIPELINE_ACCESS_KEY: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          #AWS_PIPELINE_SECRET_KEY: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
      with:
        aws-region: "ap-northeast-1"
        aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
        aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
        pipeline-name: "pplDeployCodeASGV1"
